"""
pka_weight_sweep.py — search for dynamic similarity-conditional blend weights
across {direct_xgb, analog_delta, molgpka_debiased}.

Loads pka_loo_components.npz, defines candidate weight functions of
max_tanimoto, and reports pooled / per-family LOO MAE for each.

Candidate functions (analog weight = function of max_sim s ∈ [0, 1]):
  • baseline_v91           constant w_analog=0.95, w_direct=0.05, w_molgpka=0
  • static_3comp           constant (w_d, w_a, w_m), search by grid
  • sigmoid                w_a = sigmoid(k (s - s0));   remainder split fixed
  • sigmoid_3comp          w_a = sig(k_a (s - s0)); w_m = (1-w_a)·sig(k_m (s_m - s))
  • power                  w_a = s^p
  • piecewise              piecewise-linear over anchors {0, .3, .6, .85, 1.0}
  • softmax_lin            softmax([a + b·s] over 3 components), 6 params

For each form, we minimize pooled MAE over hyperparameters with
scipy.optimize.minimize (Nelder-Mead). All evaluation is on LOO components
(no leakage — those preds were generated by holding out each compound).
"""
from __future__ import annotations
import json
import math
from pathlib import Path
from typing import Callable, Dict, List, Tuple

import numpy as np
from scipy.optimize import minimize

HERE = Path(__file__).resolve().parent
NPZ = HERE / "pka_loo_components.npz"


def _load():
    d = np.load(NPZ, allow_pickle=True)
    return {
        "direct": d["direct"], "analog": d["analog"], "molgpka": d["molgpka"],
        "max_sim": d["max_sim"], "y_true": d["y_true"],
        "families": d["families"],
    }


def _mae(pred, y): return float(np.mean(np.abs(pred - y)))


def _per_fam_mae(pred, y, fams):
    out = {}
    for f in np.unique(fams):
        m = fams == f
        out[str(f)] = {"n": int(m.sum()), "mae": _mae(pred[m], y[m])}
    return out


def _report(label, pred, data):
    pooled = _mae(pred, data["y_true"])
    per_fam = _per_fam_mae(pred, data["y_true"], data["families"])
    fam_line = "  ".join(f"{f}={per_fam[f]['mae']:.4f}(n={per_fam[f]['n']})"
                         for f in sorted(per_fam))
    print(f"  {label:25s} pooled={pooled:.4f}   {fam_line}")
    return pooled, per_fam


# ---------------------------------------------------------------------------
# Candidate weight functions: each returns weights (n,) -> tuple (w_d, w_a, w_m)
# ---------------------------------------------------------------------------

def w_baseline_v91(params, s):
    n = len(s)
    return np.full(n, 0.05), np.full(n, 0.95), np.zeros(n)


def w_static(params, s):
    """Three free params (w_d, w_a, w_m) — softmaxed to ensure simplex."""
    w = np.exp(params - np.max(params))
    w /= w.sum()
    n = len(s)
    return np.full(n, w[0]), np.full(n, w[1]), np.full(n, w[2])


def w_power(params, s):
    """w_a = s^p; remainder split (w_d, w_m) by softmax(q,r)."""
    p, q, r = params
    p = max(p, 0.01)
    w_a = np.clip(s, 0, 1) ** p
    rest = 1.0 - w_a
    z = np.exp([q, r] - np.max([q, r])); z /= z.sum()
    w_d = rest * z[0]; w_m = rest * z[1]
    return w_d, w_a, w_m


def w_sigmoid(params, s):
    """w_a = sigmoid(k (s - s0)); remainder distributed (w_d, w_m) by softmax(q,r)."""
    k, s0, q, r = params
    w_a = 1.0 / (1.0 + np.exp(-k * (s - s0)))
    rest = 1.0 - w_a
    z = np.exp([q, r] - np.max([q, r])); z /= z.sum()
    return rest * z[0], w_a, rest * z[1]


def w_sigmoid_3comp(params, s):
    """w_a = sigmoid(k_a (s - s_a))
       w_m_share = sigmoid(k_m (s_m - s))    grows as sim drops
       w_m = (1 - w_a) * w_m_share
       w_d = 1 - w_a - w_m
    """
    k_a, s_a, k_m, s_m = params
    w_a = 1.0 / (1.0 + np.exp(-k_a * (s - s_a)))
    w_m_share = 1.0 / (1.0 + np.exp(-k_m * (s_m - s)))
    w_m = (1.0 - w_a) * w_m_share
    w_d = 1.0 - w_a - w_m
    return w_d, w_a, w_m


def w_piecewise(params, s):
    """params = [w_a(s=0), w_a(s=.3), w_a(s=.6), w_a(s=.85), w_a(s=1.0),
                 share_m_at_0, share_m_at_0.3, share_m_at_0.6, share_m_at_0.85, share_m_at_1.0]
       (10 params). w_a anchors clipped to [0,1]; share_m in [0,1] via sigmoid.
    """
    anchors_s = np.array([0.0, 0.3, 0.6, 0.85, 1.0])
    w_a_anch = np.clip(np.asarray(params[:5]), 0.0, 1.0)
    share_m_anch = 1.0 / (1.0 + np.exp(-np.asarray(params[5:])))
    w_a = np.interp(s, anchors_s, w_a_anch)
    share_m = np.interp(s, anchors_s, share_m_anch)
    rest = 1.0 - w_a
    w_m = rest * share_m
    w_d = rest * (1.0 - share_m)
    return w_d, w_a, w_m


def w_softmax_lin(params, s):
    """logits_i = a_i + b_i · s for i ∈ {direct, analog, molgpka}; weights = softmax."""
    a_d, b_d, a_a, b_a, a_m, b_m = params
    L = np.stack([a_d + b_d * s, a_a + b_a * s, a_m + b_m * s], axis=1)
    L = L - L.max(axis=1, keepdims=True)
    e = np.exp(L); e = e / e.sum(axis=1, keepdims=True)
    return e[:, 0], e[:, 1], e[:, 2]


# ---------------------------------------------------------------------------
# Optimization driver
# ---------------------------------------------------------------------------

def _blend(direct, analog, molgpka, w_func, params, s):
    w_d, w_a, w_m = w_func(params, s)
    return w_d * direct + w_a * analog + w_m * molgpka


def _opt(form_name, w_func, x0, data, restarts=8, seed=0):
    rng = np.random.default_rng(seed)
    best = (np.inf, None)
    x0 = np.asarray(x0, dtype=float)
    starts = [x0]
    for _ in range(restarts - 1):
        starts.append(x0 + rng.normal(0, 0.5, size=x0.shape))
    for start in starts:
        def loss(p):
            pred = _blend(data["direct"], data["analog"], data["molgpka"],
                          w_func, p, data["max_sim"])
            return _mae(pred, data["y_true"])
        try:
            res = minimize(loss, start, method="Nelder-Mead",
                           options={"xatol": 1e-4, "fatol": 1e-5, "maxiter": 2000})
        except Exception:
            continue
        if res.fun < best[0]:
            best = (float(res.fun), res.x.copy())
    return best


def main():
    data = _load()
    print(f"Loaded LOO components for n={len(data['y_true'])} compounds.\n")

    print("Baselines:")
    _report("v9.1 baseline (α=0.05)", _blend(
        data["direct"], data["analog"], data["molgpka"],
        w_baseline_v91, None, data["max_sim"]), data)
    _report("pure direct", data["direct"], data)
    _report("pure analog", data["analog"], data)
    _report("pure molgpka", data["molgpka"], data)
    print()

    print("Optimized candidates (Nelder-Mead, 8 restarts):")
    candidates = [
        ("static_3comp",  w_static,         [0.05, 0.95, 0.01]),
        ("power",         w_power,          [1.0, 0.0, 0.0]),
        ("sigmoid",       w_sigmoid,        [10.0, 0.6, 0.0, 0.0]),
        ("sigmoid_3comp", w_sigmoid_3comp,  [10.0, 0.5, 10.0, 0.5]),
        ("piecewise",     w_piecewise,      [0.1, 0.4, 0.7, 0.9, 1.0,  0.0, 0.0, 0.0, 0.0, 0.0]),
        ("softmax_lin",   w_softmax_lin,    [0.0, 0.0, 0.0, 2.0, 0.0, 0.0]),
    ]
    results = {}
    for name, fn, x0 in candidates:
        mae, params = _opt(name, fn, x0, data, restarts=8)
        pred = _blend(data["direct"], data["analog"], data["molgpka"],
                      fn, params, data["max_sim"])
        pooled, per_fam = _report(name, pred, data)
        results[name] = {"mae": pooled, "params": params.tolist(),
                          "per_family": per_fam}

    # Pick winner
    best_name = min(results, key=lambda k: results[k]["mae"])
    print(f"\n  WINNER: {best_name}  pooled={results[best_name]['mae']:.4f}")
    print(f"  params: {results[best_name]['params']}")

    out_path = HERE / "pka_weight_sweep_results.json"
    with open(out_path, "w") as f:
        json.dump({
            "baseline_pooled_mae": 0.0653,
            "results": results,
            "winner": best_name,
        }, f, indent=2)
    print(f"\nSaved -> {out_path}")


if __name__ == "__main__":
    main()
