#!/usr/bin/env python3
"""
Produce corrected COPIES of the datasets (canonical left untouched — active overnight run).
Applies only formula-validated SMILES fixes + SI-verified pKa fixes. Updates SMILES + the
unambiguous formula/MW columns + an audit_status flag. Other feature columns are left in
place but flagged STALE (must be regenerated by the project's own pipeline — not fabricated).
Also writes a master corrections ledger.
"""
import warnings, sys, datetime; warnings.filterwarnings('ignore'); sys.path.insert(0,'audit_work')
import pandas as pd
from rdkit import Chem, RDLogger; RDLogger.DisableLog('rdApp.*')
from rdkit.Chem import Descriptors, rdMolDescriptors

PKA='IAJD_master/datasets/IAJD_pKa_v21_final.xlsx'
BIO='IAJD_master/datasets/IAJD_Bioact_v13_clean.xlsx'
corr=pd.read_csv('audit_work/ja1c05813_corrections.csv')
fixes={int(r.IAJD): r.smiles_new for _,r in corr.iterrows() if str(r.status).startswith('FIXED') and r.si_validated}
PKA_FIX={38:6.38, 45:5.93, 47:6.59}   # SI Tables S16/S17 averages

ledger=[]
def stamp(df, idcol):
    if 'audit_status' not in df.columns: df['audit_status']=''
    for iid,newsmi in fixes.items():
        m=df[idcol]==iid
        if not m.any(): continue
        old=df.loc[m,'SMILES'].iloc[0]
        if old==newsmi: continue
        df.loc[m,'SMILES']=newsmi
        mol=Chem.MolFromSmiles(newsmi)
        df.loc[m,'MolFormula']=rdMolDescriptors.CalcMolFormula(mol)
        df.loc[m,'ExactMolWt']=Descriptors.ExactMolWt(mol)
        df.loc[m,'audit_status']='SMILES_corrected_2026-06-01; FEATURES_NEED_REGEN'
        ledger.append((iid,'SMILES',old,newsmi))
    for iid,newp in PKA_FIX.items():
        m=df[idcol]==iid
        if not m.any() or 'pKa' not in df.columns: continue
        old=df.loc[m,'pKa'].iloc[0]
        if abs(float(old)-newp)<1e-6: continue
        df.loc[m,'pKa']=newp
        df.loc[m,'audit_status']=(df.loc[m,'audit_status'].iloc[0]+'; pKa_corrected_vs_SI_avg').strip('; ')
        ledger.append((iid,'pKa',old,newp))
    return df

pk=stamp(pd.read_excel(PKA),'IAJD')
pk.to_excel(PKA.replace('.xlsx','.AUDIT_FIXED.xlsx'),index=False)
bi=pd.read_excel(BIO); bi=stamp(bi,'IAJD_num')
bi.to_excel(BIO.replace('.xlsx','.AUDIT_FIXED.xlsx'),index=False)

led=pd.DataFrame(ledger,columns=['IAJD','field','old','new'])
led['paper']='ja1c05813'; led['evidence']='SI formula match (Tables S12-S17 / MALDI)'
led.to_csv('audit_work/AUDIT_corrections_master.csv',index=False)
print(f"Applied {len([l for l in ledger if l[1]=='SMILES'])} SMILES fixes + {len([l for l in ledger if l[1]=='pKa'])} pKa fixes (x2 files).")
print("Wrote *.AUDIT_FIXED.xlsx (copies) + audit_work/AUDIT_corrections_master.csv")
print(led.to_string(index=False))
